### ISSUE TITLE
关于AlexNet参数设置的疑问

### ISSUE THREAD

**Issue by abc12354a** [Zing22/tf-fed-demo#2]
作者您好，我是在CSDN上看到的文章，已经使用了您的代码验证了很多猜想，对此对您表示十分感谢和敬佩。
在使用中，我打算更换新的model的时候，发现一个问题（有可能是我自己学艺不精）
`conv2 = conv(pool1, 5, 5, 256, 1, 1, groups=2, name='conv2')
  norm2 = lrn(conv2, 2, 2e-05, 0.75, name='norm2')
  pool2 = max_pool(norm2, 3, 3, 2, 2, padding='VALID', name='pool2')
`
在第二个卷积的pool阶段，我计算大小的时候，如果不使用padding，是(2-3)/2+1，这里是我计算有误吗？程序是可以正常运行的。
详细的计算过程如下：
conv1:(32-11)/2+1 = 10.5+1 = 12
pool1:(12-3)/2+1 = 6
conv2:(6-5)/1+1 = 2
pool2:(2-3)/2=...

**Comment by Zing22** [comment]
您好，感谢您的留言。其实你可以把每一步的计算节点都输出来看看，应该能看到shape是否和你计算的一致

**Comment by abc12354a** [comment]
我测试之后又去仔细了解了一下，是padding里的same计算没有搞清楚，谢谢解惑！
